### ISSUE TITLE
Assignment 3 - Number of words

### ISSUE THREAD

**Issue by HC94** [RUG-IDS/Assignments#10]
Hello,

On the sheet of assignment 3 it is mentioned that we should aim for 1,800 words in our report. Is this just an indication? What if we deviates from this by `a lot', e.g. 1000 or 3500 words?

**Comment by kbunte** [comment]
Hello,
it is meant as a guideline for you on how much we expect and to prevent you from writing 20 pages. In conferences and journals you face occasionally pretty strict format restrictions, so you need to be concise. Deviations of 500 words are still acceptable for us counting the mandatory content. In case you decided to deal with the Bonus topics, so explain much more than the mandatory content, you get another 1,800 words.

**Comment by wouterRUG** [comment]
I suspect that the words for the questions and answers are excluded for the word count, aren't they? 

Is it OK if we simply put the Q&A and distribution of work into some appendix of the report and disregard those words? 
(Hopefully!)

**Comment by kbunte** [comment]
We meant aiming for ca. 1800 words as a guideline, if you need a little more and if you not exaggerate it is still ok. The non-trivial questions can be put in the appendix and they can be disregarded from the count.

In case your team did not contribute equally to the assignment note this in a SEPARATE file (since the report will be provided to everybody as learning material).

**Comment by wouterRUG** [comment]
Thank you for your answer. 

We have a kind of luxurious problem, because we have such an interesting subject that we can spend all day talking and writing about it. Right now, for just the main part, we have already double the amount of words...

We will try to minimize the amount of words by simply deleting some subsections, because 3500 words are significantly too much I think...

Thanks.

**Comment by kbunte** [comment]
Hello, I am very pleased that you find your topic interesting. However, you are right that 3500 words are quite a lot. Try to be concise where ever possible and instead of deleting subsections you may put them into an appendix. This is a procedure which is also known for journal publications when the space is simply not enough to put all relevant information. The main part of the contribution contains than all necessary information and additional detailed explanation or addition is referenced to be found in the supplementary material/section/appendix. 
I think this is a good compromise, so we still provide the results of all your effort in the material and do not put too much additional work load on you.
