### ISSUE TITLE
Clarifications Assignment 3

### ISSUE THREAD

**Issue by michel-medema** [RUG-IDS/Assignments#12]
Assignment 3 requests a report where one of the parts of the report should be "Main study, demonstration of problems", however, this seems rather broad and vague. Would it be possible to provide some additional information regarding what is expected in this section? For example, should it be research oriented (e.g. should some small research be performed for the topic) or should it only provide information and describe some of the techniques related to the topic along with some examples to demonstrate how the techniques work?

For the three questions related to the topic it is also somewhat unclear what is expected there. What kinds of questions could be thought of here? Moreover, as it is presented in the assignment description, this part seems to be completely separate from the report. Is this indeed the case or is it possible/required to use these questions in the report, for example in the main study?

**Comment by kbunte** [comment]
The part "Main study, demonstration of problems" was formulated vague since de exact expectations may vary a bit dependent on the topic. Please refer back to assignment 2 for the specific requirements for each individual topic (provide general information, describe the main techniques as mentioned in assignment 2 and provide examples). Research oriented content can be provided voluntarily as suggested in the bonus part, but is not mandatory. 
The questions can be put in the appendix when they are not directly connected to the introduction or conclusion. After the presentation usually some questions were ask from the audience, those can be good candidates for that part of the assignment. I heard often e.g. questions with regard to CPU and Memory efficiency.
