### ISSUE TITLE
Feedback on assignments 1/2 (related to 3)

### ISSUE THREAD

**Issue by Hoeksema** [RUG-IDS/Assignments#9]
I was wondering when we can expect to receive feedback on assignment 1?

Also, since assignment 3 is related to assignment 2, would it be possible to receive the feedback on assignment 2 before the deadline of assignment 3?

It's not necessary, it's just a request since it could be helpful. Thanks in advance either way!

**Comment by kbunte** [comment]
Hello,
first of all we are very happy about the overall quality and effort of the presentation session. 
In general the grades of the assignments can be expected to be uploaded within 2 weeks after handing them in, but we are nearly done with assignment 1 and plan to upload the results at the end of the week.

We asked to upload the feedback during the day, therefore I can distribute the anonymized data to the corresponding groups only by the end of the week.

General information (since I was asked after the presentation session):
We plan to make all team reports available together with an information file, which contains a ranking (not the grading!) of the material and remarks for you (as for example: "a very nice example is given in report #x", "further references and background material was provided by #y", and so on)
